name: GetUUID
version: '${version}'
main: art.ryanstew.getuuid.GetUUID
api-version: '1.20'
author: RuntimeRyn

commands:
    getuuid:
        description: Get the UUID of a player by their name!
        permission: getuuid.use
        aliases: [playeruuid]

permissions:
    getuuid.use:
        description: Permission to use /getuuid.
        default: op
    getuuid.reload:
        description: Permission to use /getuuid reload.
        default: op
